// Generated by Wrangler by running `wrangler types`

interface Env {
	TG_TOKEN: string;
	GOOGLE_API_KEY: string;
	CUSTOM_SEARCH_ENGINE_ID: string;
	BOT_USERNAME: string;
	MISTRAL_API_KEY: string;
	CF_ACCOUNT_ID: string;
	AI_GATEWAY_ID: string;
	NODE_ENV: string;
	MISTRAL_AGENT_ID: string;
	STICKER_SETS: string;
	DB: D1Database;
}
