name = "picture-bot"
main = "src/index.ts"
compatibility_date = "2024-12-11"
compatibility_flags = ["nodejs_compat"]

upload_source_maps = true

[observability.logs]
enabled = true
invocation_logs = false

[[d1_databases]]
binding = "DB"
database_name = "picture-bot"
database_id = "ce6528dd-68e9-4784-803e-8a364f8fce00"